# Site settings
title: Adam Wilson Lab
email: adamw@Buffalo.edu
description: Adam M. Wilson, Department of Geography, University at Buffalo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "adamwilson.us" #http://adamwilson.us" # the base hostname & protocol for your site
twitter_username: AdamWilsonLab
github_username:  AdamMWilson

# Build settings
markdown: kramdown

#paginate: 4
#paginate_path: "blog/page:num"
